export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const CHANGE_TASK = 'CHANGE_TASK';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const ADD_COUNT_CATEGORY = 'ADD_COUNT_CATEGORY';
export const SUBTRACT_COUNT_CATEGORY = 'SUBTRACT_COUNT_CATEGORY';

export const CHANGE_ACTIVECATEGORY = 'CHANGE_ACTIVECATEGORY';

export const CHANGE_ACTIVEFILTER = 'CHANGE_ACTIVEFILTER';